[package]
edition = "2018"
name = "{{project-name}}"
version = "0.0.0"
authors = ["{{authors}}"]
publish = false
description = ""
readme = "README.md"
keywords = []
categories = []
license = "MIT OR Apache-2.0"
repository = "https://github.com/qryxip/{{project-name}}"

[dependencies]
